Repository jisung-in/backend, pull requests merged in 2024-05, with the labels that each got.

#93 [Feature] 로그 추적기 구현
  src/main/java/com/jisungin/JisunginApplication.java
  src/main/java/com/jisungin/trace/LogTraceAspect.java
  src/main/java/com/jisungin/trace/TraceId.java
  src/main/java/com/jisungin/trace/TraceStatus.java
  src/main/java/com/jisungin/trace/logtrace/LogTrace.java
  src/main/java/com/jisungin/trace/logtrace/ThreadLocalLogTrace.java
Labels: ✨ Feature

#79 [Deploy] 프론트 연동을 위한 코드 수정
  src/main/java/com/jisungin/api/oauth/AuthInterceptor.java
  src/main/java/com/jisungin/api/oauth/OauthController.java
  src/main/java/com/jisungin/config/WebConfig.java
  src/main/resources/application.yml
Labels: 🌏 Deploy

#95 [Refactor] Search Request 제거
  src/docs/asciidoc/api/comment/comment.adoc
  src/main/java/com/jisungin/api/Offset.java
  src/main/java/com/jisungin/api/talkroom/TalkRoomController.java
  src/main/java/com/jisungin/application/PageServiceRequest.java
  src/main/java/com/jisungin/application/talkroom/TalkRoomService.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryCustom.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryImpl.java
  src/test/java/com/jisungin/application/talkroom/TalkRoomServiceTest.java
  src/test/java/com/jisungin/docs/talkroom/TalkRoomControllerDocsTest.java
Labels: 🔨 Refactor

#97 [BugFix] 로그인 시 유저 ID값을 받도록 수정
  src/main/java/com/jisungin/api/comment/CommentController.java
  src/main/java/com/jisungin/api/oauth/AuthInterceptor.java
  src/main/java/com/jisungin/config/AuthConfig.java
  src/test/java/com/jisungin/ControllerTestSupport.java
  src/test/java/com/jisungin/api/comment/CommentControllerTest.java
  src/test/java/com/jisungin/api/commentlike/CommentLikeControllerTest.java
  src/test/java/com/jisungin/api/review/ReviewControllerTest.java
  src/test/java/com/jisungin/api/reviewlike/ReviewLikeControllerTest.java
  src/test/java/com/jisungin/api/talkroom/TalkRoomControllerTest.java
  src/test/java/com/jisungin/api/talkroomlike/TalkRoomLikeControllerTest.java
  src/test/java/com/jisungin/api/user/UserControllerTest.java
  src/test/java/com/jisungin/api/userlibrary/UserLibraryControllerTest.java
Labels: 🐞 BugFix

#103 [Refactor] TalkRoom 데이터 총 개수 Query 분리
  src/main/java/com/jisungin/api/comment/CommentController.java
  src/main/java/com/jisungin/api/talkroom/TalkRoomController.java
  src/main/java/com/jisungin/application/comment/CommentFindAllResponse.java
  src/main/java/com/jisungin/application/comment/CommentService.java
  src/main/java/com/jisungin/application/comment/response/CommentPageResponse.java
  src/main/java/com/jisungin/application/comment/response/CommentQueryResponse.java
  src/main/java/com/jisungin/application/talkroom/TalkRoomService.java
  src/main/java/com/jisungin/config/SecurityConfig.java
  src/main/java/com/jisungin/domain/comment/Comment.java
  src/main/java/com/jisungin/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/jisungin/domain/commentimage/repository/CommentImageRepository.java
  src/main/java/com/jisungin/domain/commentimage/repository/CommentImageRepositoryCustom.java
  src/main/java/com/jisungin/domain/commentimage/repository/CommentImageRepositoryImpl.java
  src/main/java/com/jisungin/domain/commentlike/repository/CommentLikeRepository.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryCustom.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryImpl.java
  src/main/java/com/jisungin/domain/userlibrary/repository/UserLibraryRepository.java
  src/test/java/com/jisungin/api/comment/CommentControllerTest.java
  src/test/java/com/jisungin/api/talkroom/TalkRoomControllerTest.java
  src/test/java/com/jisungin/application/comment/CommentServiceTest.java
  src/test/java/com/jisungin/application/talkroom/TalkRoomServiceTest.java
  src/test/java/com/jisungin/docs/comment/CommentControllerDocsTest.java
  src/test/java/com/jisungin/docs/talkroom/TalkRoomControllerDocsTest.java
Labels: 🔨 Refactor

#106 [Feature] 나의 토크방 모아보기 API 구현
  src/docs/asciidoc/api/talkroom/talkroom.adoc
  src/main/java/com/jisungin/api/talkroom/TalkRoomController.java
  src/main/java/com/jisungin/application/comment/CommentFindAllResponse.java
  src/main/java/com/jisungin/application/comment/CommentService.java
  src/main/java/com/jisungin/application/talkroom/TalkRoomService.java
  src/main/java/com/jisungin/application/talkroom/response/TalkRoomFindAllResponse.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepository.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryCustom.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryImpl.java
  src/main/java/com/jisungin/domain/talkroomlike/repository/TalkRoomLikeRepositoryCustom.java
  src/main/java/com/jisungin/domain/userlibrary/repository/UserLibraryRepository.java
  src/test/java/com/jisungin/api/talkroom/TalkRoomControllerTest.java
  src/test/java/com/jisungin/application/comment/CommentServiceTest.java
  src/test/java/com/jisungin/application/talkroom/TalkRoomServiceTest.java
  src/test/java/com/jisungin/docs/talkroom/TalkRoomControllerDocsTest.java
  src/test/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryTest.java
Labels: ✨ Feature

#107 [Docs] 마이페이지 API REST Docs 작성
  src/docs/asciidoc/api/rating/rating.adoc
  src/docs/asciidoc/api/review/review.adoc
  src/docs/asciidoc/api/user/user.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/jisungin/api/rating/RatingController.java
  src/main/java/com/jisungin/api/review/ReviewController.java
  src/main/java/com/jisungin/api/user/UserController.java
  src/main/java/com/jisungin/application/rating/RatingService.java
  src/main/java/com/jisungin/application/rating/response/RatingCreateResponse.java
  src/main/java/com/jisungin/application/rating/response/RatingGetOneResponse.java
  src/main/java/com/jisungin/application/user/UserService.java
  src/main/java/com/jisungin/application/user/response/UserInfoResponse.java
  src/main/java/com/jisungin/config/SecurityConfig.java
  src/main/java/com/jisungin/domain/rating/repository/RatingRepository.java
  src/main/java/com/jisungin/exception/ErrorCode.java
  src/test/java/com/jisungin/api/user/UserControllerTest.java
  src/test/java/com/jisungin/application/rating/RatingServiceTest.java
  src/test/java/com/jisungin/application/user/UserServiceTest.java
  src/test/java/com/jisungin/docs/rating/RatingControllerDocsTest.java
  src/test/java/com/jisungin/docs/review/ReviewControllerDocsTest.java
  src/test/java/com/jisungin/docs/user/UserControllerDocsTest.java
Labels: 📃 Docs

#108 [Feature] 도서와 관련된 리뷰 조회 API 구현
  src/docs/asciidoc/api/review/review.adoc
  src/main/java/com/jisungin/api/review/ReviewController.java
  src/main/java/com/jisungin/application/OffsetLimit.java
  src/main/java/com/jisungin/application/SliceResponse.java
  src/main/java/com/jisungin/application/review/ReviewService.java
  src/main/java/com/jisungin/application/review/response/ReviewWithRatingResponse.java
  src/main/java/com/jisungin/domain/review/ReviewOrderType.java
  src/main/java/com/jisungin/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/jisungin/domain/review/repository/ReviewRepositoryImpl.java
  src/test/java/com/jisungin/api/review/ReviewControllerTest.java
  src/test/java/com/jisungin/application/review/ReviewServiceTest.java
  src/test/java/com/jisungin/docs/review/ReviewControllerDocsTest.java
  src/test/java/com/jisungin/domain/review/repository/ReviewRepositoryTest.java
Labels: ✨ Feature

#114 [Feature] Review 사용자 아이디 필드 추가
  src/main/java/com/jisungin/api/review/ReviewController.java
  src/main/java/com/jisungin/application/review/response/ReviewWithRatingResponse.java
  src/main/java/com/jisungin/application/user/UserService.java
  src/main/java/com/jisungin/application/user/response/UserInfoResponse.java
  src/main/java/com/jisungin/domain/review/repository/ReviewRepositoryImpl.java
  src/test/java/com/jisungin/application/user/UserServiceTest.java
  src/test/java/com/jisungin/docs/review/ReviewControllerDocsTest.java
  src/test/java/com/jisungin/docs/user/UserControllerDocsTest.java
Labels: ✨ Feature

#116 [Feature] 한줄평 관련 API 수정, 독서 상태 REST Docs 추가
  src/docs/asciidoc/api/userlibrary/userlibrary.adoc
  src/main/java/com/jisungin/application/rating/RatingService.java
  src/main/java/com/jisungin/application/review/response/ReviewContentResponse.java
  src/main/java/com/jisungin/application/userlibrary/response/UserReadingStatusResponse.java
  src/main/java/com/jisungin/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/jisungin/domain/userlibrary/repository/UserLibraryRepositoryImpl.java
  src/test/java/com/jisungin/application/rating/RatingServiceTest.java
  src/test/java/com/jisungin/docs/user/UserControllerDocsTest.java
Labels: ✨ Feature, 📃 Docs
