Repository jisung-in/backend, pull requests merged in 2024-04, with the labels that each got.

#55 [Feature] 베스트 셀러 Redis 조회 기능 및 스케쥴링 구현
  .github/workflows/jisungin_dev.yml
  build.gradle
  docker-compose.yml
  src/main/java/com/jisungin/JisunginApplication.java
  src/main/java/com/jisungin/api/book/BookController.java
  src/main/java/com/jisungin/api/book/request/BookCreateRequest.java
  src/main/java/com/jisungin/api/book/request/BookPageRequest.java
  src/main/java/com/jisungin/application/book/BestSellerService.java
  src/main/java/com/jisungin/application/book/BookService.java
  src/main/java/com/jisungin/application/book/event/BestSellerUpdatedEvent.java
  src/main/java/com/jisungin/application/book/event/BestSellerUpdatedEventListener.java
  src/main/java/com/jisungin/application/book/request/BookCreateServiceRequest.java
  src/main/java/com/jisungin/application/book/request/BookServicePageRequest.java
  src/main/java/com/jisungin/application/book/response/BestSellerResponse.java
  src/main/java/com/jisungin/application/book/response/BookResponse.java
  src/main/java/com/jisungin/config/AsyncConfig.java
  src/main/java/com/jisungin/config/RedisConfig.java
  src/main/java/com/jisungin/domain/book/Book.java
  src/main/java/com/jisungin/domain/book/repository/BestSellerRedisRepository.java
  src/main/java/com/jisungin/domain/book/repository/BestSellerRepository.java
  src/main/java/com/jisungin/domain/comment/Comment.java
  src/main/java/com/jisungin/domain/review/Review.java
  src/main/java/com/jisungin/domain/talkroom/TalkRoom.java
  src/main/java/com/jisungin/exception/ErrorCode.java
  src/main/java/com/jisungin/infra/crawler/CrawlingBook.java
  src/main/java/com/jisungin/infra/crawler/Yes24Crawler.java
  src/main/java/com/jisungin/infra/crawler/Yes24Fetcher.java
  src/main/java/com/jisungin/infra/crawler/Yes24Parser.java
  src/main/java/com/jisungin/infra/scheduler/BestSellerScheduler.java
  src/main/java/com/jisungin/infra/scheduler/BestSellerTaskExecutor.java
  src/main/resources/application-local.yml
  src/test/java/com/jisungin/ControllerTestSupport.java
  src/test/java/com/jisungin/RedisTestContainer.java
  src/test/java/com/jisungin/api/book/BookControllerTest.java
  src/test/java/com/jisungin/application/service/book/BestSellerServiceTest.java
  src/test/java/com/jisungin/application/service/book/BookServiceTest.java
  src/test/resources/application.yml
Labels: ✨ Feature

#59 [Feature] 리뷰 좋아요 API 구현
  src/main/java/com/jisungin/api/reviewlike/ReviewLikeController.java
  src/main/java/com/jisungin/application/reviewlike/ReviewLikeService.java
  src/main/java/com/jisungin/domain/reviewlike/ReviewLike.java
  src/main/java/com/jisungin/domain/reviewlike/repository/ReviewLikeRepository.java
  src/main/java/com/jisungin/exception/ErrorCode.java
  src/test/java/com/jisungin/ControllerTestSupport.java
  src/test/java/com/jisungin/api/reviewlike/ReviewLikeControllerTest.java
  src/test/java/com/jisungin/application/reviewlike/ReviewLikeServiceTest.java
Labels: ✨ Feature

#60 [Feature] TalkRoom 의견 이미지를 S3를 통해 저장 기능 구현
  .github/workflows/jisungin_dev.yml
  .gitignore
  build.gradle
  src/docs/asciidoc/api/image/image.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/jisungin/api/image/ImageController.java
  src/main/java/com/jisungin/application/image/ImageService.java
  src/main/java/com/jisungin/config/S3Config.java
  src/main/java/com/jisungin/exception/ErrorCode.java
  src/main/java/com/jisungin/infra/s3/S3FileManager.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/com/jisungin/ControllerTestSupport.java
  src/test/java/com/jisungin/JisunginApplicationTests.java
  src/test/java/com/jisungin/ServiceTestSupport.java
  src/test/java/com/jisungin/api/image/ImageControllerTest.java
  src/test/java/com/jisungin/application/image/ImageServiceTest.java
  src/test/java/com/jisungin/application/service/book/BestSellerServiceTest.java
  src/test/java/com/jisungin/docs/image/ImageControllerDocsTest.java
  src/test/resources/org.springframework/restdocs/templates/path-parameters.snippet
  src/test/resources/org.springframework/restdocs/templates/query-parameters.snippet
  src/test/resources/org.springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org.springframework/restdocs/templates/respnse-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/query-parameters.snippet
Labels: ✨ Feature

#63 [Refactor] TalkRoom 조회 Query 리펙토링
  src/main/java/com/jisungin/api/SearchRequest.java
  src/main/java/com/jisungin/api/comment/CommentController.java
  src/main/java/com/jisungin/api/talkroom/TalkRoomController.java
  src/main/java/com/jisungin/api/talkroom/request/TalkRoomCreateRequest.java
  src/main/java/com/jisungin/api/talkroom/request/TalkRoomEditRequest.java
  src/main/java/com/jisungin/application/PageResponse.java
  src/main/java/com/jisungin/application/SearchServiceRequest.java
  src/main/java/com/jisungin/application/comment/CommentService.java
  src/main/java/com/jisungin/application/comment/response/CommentQueryResponse.java
  src/main/java/com/jisungin/application/talkroom/TalkRoomService.java
  src/main/java/com/jisungin/application/talkroom/request/TalkRoomCreateServiceRequest.java
  src/main/java/com/jisungin/application/talkroom/request/TalkRoomEditServiceRequest.java
  src/main/java/com/jisungin/application/talkroom/response/TalkRoomFindAllResponse.java
  src/main/java/com/jisungin/application/talkroom/response/TalkRoomFindOneResponse.java
  src/main/java/com/jisungin/application/talkroom/response/TalkRoomResponse.java
  src/main/java/com/jisungin/domain/comment/repository/CommentRepository.java
  src/main/java/com/jisungin/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/jisungin/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/jisungin/domain/commentlike/repository/CommentLikeRepository.java
  src/main/java/com/jisungin/domain/talkroom/repository/OrderType.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryCustom.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryImpl.java
  src/main/java/com/jisungin/domain/talkroomimage/TalkRoomImage.java
  src/main/java/com/jisungin/domain/talkroomimage/repository/TalkRoomImageRepository.java
  src/main/java/com/jisungin/domain/talkroomlike/repository/TalkRoomLikeRepository.java
  src/test/java/com/jisungin/api/comment/CommentControllerTest.java
  src/test/java/com/jisungin/api/talkroom/TalkRoomControllerTest.java
  src/test/java/com/jisungin/application/comment/CommentServiceTest.java
  src/test/java/com/jisungin/application/talkroom/TalkRoomServiceTest.java
  src/test/java/com/jisungin/docs/comment/CommentControllerDocsTest.java
  src/test/java/com/jisungin/docs/talkroom/TalkRoomControllerDocsTest.java
  src/test/java/com/jisungin/domain/comment/repository/CommentRepositoryImplTest.java
  src/test/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryTest.java
  src/test/resources/org/springframework/restdocs/templates/path-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/query-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/respnse-fields.snippet
Labels: 🔨 Refactor

#69 [Feature] TalkRoom 조회 시 이미지 URL 추가
  src/main/java/com/jisungin/api/talkroom/TalkRoomController.java
  src/main/java/com/jisungin/application/PageResponse.java
  src/main/java/com/jisungin/application/comment/CommentService.java
  src/main/java/com/jisungin/application/talkroom/TalkRoomService.java
  src/main/java/com/jisungin/application/talkroom/response/TalkRoomFindAllResponse.java
  src/main/java/com/jisungin/application/talkroom/response/TalkRoomFindOneResponse.java
  src/main/java/com/jisungin/application/talkroom/response/TalkRoomPageResponse.java
  src/main/java/com/jisungin/application/talkroom/response/TalkRoomResponse.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryCustom.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryImpl.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRoleRepositoryCustom.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRoleRepositoryImpl.java
  src/main/java/com/jisungin/domain/talkroomimage/repository/TalkRoomImageQueryResponse.java
  src/main/java/com/jisungin/domain/talkroomimage/repository/TalkRoomImageRepository.java
  src/main/java/com/jisungin/domain/talkroomimage/repository/TalkRoomImageRepositoryCustom.java
  src/main/java/com/jisungin/domain/talkroomimage/repository/TalkRoomImageRepositoryImpl.java
  src/main/java/com/jisungin/domain/talkroomlike/repository/TalkRoomLikeRepository.java
  src/main/java/com/jisungin/domain/talkroomlike/repository/TalkRoomLikeRepositoryCustom.java
  src/main/java/com/jisungin/domain/talkroomlike/repository/TalkRoomLikeRepositoryImpl.java
  src/test/java/com/jisungin/api/talkroom/TalkRoomControllerTest.java
  src/test/java/com/jisungin/application/comment/CommentServiceTest.java
  src/test/java/com/jisungin/application/talkroom/TalkRoomServiceTest.java
  src/test/java/com/jisungin/docs/RestDocsSupport.java
  src/test/java/com/jisungin/docs/comment/CommentControllerDocsTest.java
  src/test/java/com/jisungin/docs/talkroom/TalkRoomControllerDocsTest.java
  src/test/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryTest.java
  src/test/java/com/jisungin/domain/talkroomimage/repository/TalkRoomImageRepositoryTest.java
Labels: ✨ Feature, 🔨 Refactor

#70 [Feature] 실시간 검색어 API 구현
  src/main/java/com/jisungin/api/search/SearchController.java
  src/main/java/com/jisungin/api/search/request/SearchKeywordRequest.java
  src/main/java/com/jisungin/application/search/SearchService.java
  src/main/java/com/jisungin/config/RedisConfig.java
  src/test/java/com/jisungin/ControllerTestSupport.java
  src/test/java/com/jisungin/api/search/SearchControllerTest.java
  src/test/java/com/jisungin/application/search/SearchServiceTest.java
Labels: ✨ Feature

#72 [Feature] 최근 등록된 책 조회 API 구현
  src/main/java/com/jisungin/api/SearchRequest.java
  src/main/java/com/jisungin/api/book/BookController.java
  src/main/java/com/jisungin/application/book/BookService.java
  src/main/java/com/jisungin/application/book/response/SimpleBookResponse.java
  src/main/java/com/jisungin/domain/book/repository/BookRepository.java
  src/main/java/com/jisungin/domain/book/repository/BookRepositoryCustom.java
  src/main/java/com/jisungin/domain/book/repository/BookRepositoryImpl.java
  src/main/java/com/jisungin/domain/talkroom/repository/OrderType.java
  src/test/java/com/jisungin/api/book/BookControllerTest.java
  src/test/java/com/jisungin/application/book/BestSellerServiceTest.java
  src/test/java/com/jisungin/application/book/BookServiceTest.java
  src/test/java/com/jisungin/domain/book/repository/BookRepositoryTest.java
Labels: ✨ Feature

#75 [Refactor] Comment 리펙토링
  src/main/java/com/jisungin/api/comment/CommentController.java
  src/main/java/com/jisungin/application/comment/CommentService.java
  src/main/java/com/jisungin/application/comment/response/CommentPageResponse.java
  src/main/java/com/jisungin/application/comment/response/CommentQueryResponse.java
  src/main/java/com/jisungin/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/jisungin/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/jisungin/domain/mylibrary/repository/UserLibraryRepository.java
  src/main/java/com/jisungin/exception/ErrorCode.java
  src/test/java/com/jisungin/application/comment/CommentServiceTest.java
  src/test/java/com/jisungin/docs/comment/CommentControllerDocsTest.java
  src/test/java/com/jisungin/docs/talkroom/TalkRoomControllerDocsTest.java
  src/test/java/com/jisungin/domain/comment/repository/CommentRepositoryImplTest.java
Labels: 🔨 Refactor

#76 [Feature] UserLibrary CRUD 기능 구현
  src/main/java/com/jisungin/api/ApiResponse.java
  src/main/java/com/jisungin/api/GlobalExceptionHandler.java
  src/main/java/com/jisungin/api/userlibrary/UserLibraryController.java
  src/main/java/com/jisungin/api/userlibrary/request/UserLibraryCreateRequest.java
  src/main/java/com/jisungin/api/userlibrary/request/UserLibraryEditRequest.java
  src/main/java/com/jisungin/application/userlibrary/UserLibraryService.java
  src/main/java/com/jisungin/application/userlibrary/request/UserLibraryCreateServiceRequest.java
  src/main/java/com/jisungin/application/userlibrary/request/UserLibraryEditServiceRequest.java
  src/main/java/com/jisungin/application/userlibrary/response/UserLibraryResponse.java
  src/main/java/com/jisungin/domain/ReadingStatus.java
  src/main/java/com/jisungin/domain/book/Book.java
  src/main/java/com/jisungin/domain/mylibrary/UserLibrary.java
  src/main/java/com/jisungin/domain/mylibrary/repository/UserLibraryRepository.java
  src/main/java/com/jisungin/exception/ErrorCode.java
  src/test/java/com/jisungin/ControllerTestSupport.java
  src/test/java/com/jisungin/api/userlibrary/UserLibraryControllerTest.java
  src/test/java/com/jisungin/application/userlibrary/UserLibraryServiceTest.java
Labels: ✨ Feature

#77 [Feature] 사용자 독서 상태 조회 API 구현
  src/main/java/com/jisungin/api/user/UserController.java
  src/main/java/com/jisungin/api/user/request/UserReadingStatusGetAllRequest.java
  src/main/java/com/jisungin/application/comment/CommentService.java
  src/main/java/com/jisungin/application/user/UserService.java
  src/main/java/com/jisungin/application/user/request/UserReadingStatusGetAllServiceRequest.java
  src/main/java/com/jisungin/application/userlibrary/UserLibraryService.java
  src/main/java/com/jisungin/application/userlibrary/request/UserLibraryCreateServiceRequest.java
  src/main/java/com/jisungin/application/userlibrary/response/UserLibraryResponse.java
  src/main/java/com/jisungin/application/userlibrary/response/UserReadingStatusResponse.java
  src/main/java/com/jisungin/domain/ReadingStatus.java
  src/main/java/com/jisungin/domain/userlibrary/ReadingStatusOrderType.java
  src/main/java/com/jisungin/domain/userlibrary/UserLibrary.java
  src/main/java/com/jisungin/domain/userlibrary/repository/UserLibraryRepository.java
  src/main/java/com/jisungin/domain/userlibrary/repository/UserLibraryRepositoryCustom.java
  src/main/java/com/jisungin/domain/userlibrary/repository/UserLibraryRepositoryImpl.java
  src/test/java/com/jisungin/api/user/UserControllerTest.java
  src/test/java/com/jisungin/application/comment/CommentServiceTest.java
  src/test/java/com/jisungin/application/user/UserServiceTest.java
  src/test/java/com/jisungin/application/userlibrary/UserLibraryServiceTest.java
  src/test/java/com/jisungin/domain/userlibrary/repository/UserLibraryRepositoryImplTest.java
Labels: ✨ Feature

#82 [Feature] 의견 등록 시 이미지 업로드 기능 추가
  src/main/java/com/jisungin/api/comment/request/CommentCreateRequest.java
  src/main/java/com/jisungin/api/comment/request/CommentEditRequest.java
  src/main/java/com/jisungin/application/comment/CommentService.java
  src/main/java/com/jisungin/application/comment/request/CommentCreateServiceRequest.java
  src/main/java/com/jisungin/application/comment/request/CommentEditServiceRequest.java
  src/main/java/com/jisungin/application/comment/response/CommentResponse.java
  src/main/java/com/jisungin/application/talkroom/TalkRoomService.java
  src/main/java/com/jisungin/domain/commentimage/CommentImage.java
  src/main/java/com/jisungin/domain/commentimage/repository/CommentImageRepository.java
  src/test/java/com/jisungin/application/comment/CommentServiceTest.java
  src/test/java/com/jisungin/docs/comment/CommentControllerDocsTest.java
Labels: ✨ Feature

#84 [Docs] Book REST Docs 작성
  src/docs/asciidoc/api/book/book.adoc
  src/docs/asciidoc/index.adoc
  src/test/java/com/jisungin/docs/book/BookControllerDocsTest.java
Labels: 📃 Docs

#88 [Docs] UserLibrary REST Docs 작성
  src/docs/asciidoc/api/userlibrary/userlibrary.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/jisungin/api/userlibrary/UserLibraryController.java
  src/main/java/com/jisungin/application/userlibrary/UserLibraryService.java
  src/test/java/com/jisungin/api/userlibrary/UserLibraryControllerTest.java
  src/test/java/com/jisungin/application/userlibrary/UserLibraryServiceTest.java
  src/test/java/com/jisungin/docs/userlibrary/UserLibraryControllerDocsTest.java
Labels: 📃 Docs
