Repository jisung-in/backend, pull requests merged in 2024-03, with the labels that each got.

#5 [Feature] 예외 처리 로직 및 API Response 구현
  src/main/java/com/jisungin/api/ApiResponse.java
  src/main/java/com/jisungin/api/GlobalExceptionHandler.java
  src/main/java/com/jisungin/exception/BusinessException.java
  src/main/java/com/jisungin/exception/ErrorCode.java
  src/main/java/com/jisungin/exception/ErrorResponse.java
Labels: ✨ Feature

#6 [Feature] TalkRoom 생성 API 구현
  src/main/java/com/jisungin/api/talkroom/TalkRoomController.java
  src/main/java/com/jisungin/api/talkroom/request/TalkRoomCreateRequest.java
  src/main/java/com/jisungin/application/talkroom/TalkRoomService.java
  src/main/java/com/jisungin/application/talkroom/request/TalkRoomCreateServiceRequest.java
  src/main/java/com/jisungin/application/talkroom/response/TalkRoomResponse.java
  src/main/java/com/jisungin/domain/ReadingStatus.java
  src/main/java/com/jisungin/domain/book/repository/BookRepository.java
  src/main/java/com/jisungin/domain/talkroom/TalkRoom.java
  src/main/java/com/jisungin/domain/talkroom/TalkRoomRole.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepository.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRoleRepository.java
  src/main/java/com/jisungin/domain/user/repository/UserRepository.java
  src/main/java/com/jisungin/exception/ErrorCode.java
  src/test/java/com/jisungin/api/talkroom/TalkRoomControllerTest.java
  src/test/java/com/jisungin/application/service/talkroom/TalkRoomServiceTest.java
Labels: ✨ Feature

#11 [Feature] 소셜 로그인 구현
  .gitignore
  build.gradle
  src/main/java/com/jisungin/JisunginApplication.java
  src/main/java/com/jisungin/api/oauth/OauthController.java
  src/main/java/com/jisungin/api/oauth/OauthTypeConverter.java
  src/main/java/com/jisungin/application/oauth/OauthService.java
  src/main/java/com/jisungin/config/WebConfig.java
  src/main/java/com/jisungin/domain/oauth/OauthId.java
  src/main/java/com/jisungin/domain/oauth/OauthType.java
  src/main/java/com/jisungin/domain/oauth/authcode/AuthCodeRequestUrlProvider.java
  src/main/java/com/jisungin/domain/oauth/authcode/AuthCodeRequestUrlProviderComposite.java
  src/main/java/com/jisungin/domain/oauth/client/UserClient.java
  src/main/java/com/jisungin/domain/oauth/client/UserClientComposite.java
  src/main/java/com/jisungin/domain/user/User.java
  src/main/java/com/jisungin/domain/user/repository/UserRepository.java
  src/main/java/com/jisungin/exception/ErrorCode.java
  src/main/java/com/jisungin/infra/oauth/authcode/KakaoAuthCodeRequestUrlProvider.java
  src/main/java/com/jisungin/infra/oauth/config/HttpInterfaceConfig.java
  src/main/java/com/jisungin/infra/oauth/kakao/KakaoOauthConfig.java
  src/main/java/com/jisungin/infra/oauth/kakao/KakaoUserClient.java
  src/main/java/com/jisungin/infra/oauth/kakao/client/KakaoApiClient.java
  src/main/java/com/jisungin/infra/oauth/kakao/dto/KakaoToken.java
  src/main/java/com/jisungin/infra/oauth/kakao/dto/KakaoUserResponse.java
  src/main/resources/application.yml
Labels: ✨ Feature

#13 [Feature] TalkRoom 수정 API 구현
  src/main/java/com/jisungin/api/talkroom/TalkRoomController.java
  src/main/java/com/jisungin/api/talkroom/request/TalkRoomEditRequest.java
  src/main/java/com/jisungin/application/talkroom/TalkRoomService.java
  src/main/java/com/jisungin/application/talkroom/request/TalkRoomEditServiceRequest.java
  src/main/java/com/jisungin/domain/talkroom/TalkRoom.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepository.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRoleRepository.java
  src/main/java/com/jisungin/domain/user/User.java
  src/main/java/com/jisungin/exception/ErrorCode.java
  src/test/java/com/jisungin/api/talkroom/TalkRoomControllerTest.java
  src/test/java/com/jisungin/application/service/talkroom/TalkRoomServiceTest.java
Labels: ✨ Feature

#15 [Feature] Book 단건 조회 API 구현
  src/main/java/com/jisungin/api/book/BookController.java
  src/main/java/com/jisungin/api/talkroom/request/TalkRoomCreateRequest.java
  src/main/java/com/jisungin/application/book/BookService.java
  src/main/java/com/jisungin/application/book/response/BookResponse.java
  src/main/java/com/jisungin/application/talkroom/TalkRoomService.java
  src/main/java/com/jisungin/application/talkroom/request/TalkRoomCreateServiceRequest.java
  src/main/java/com/jisungin/domain/book/Book.java
  src/main/java/com/jisungin/domain/book/repository/BookRepository.java
  src/main/java/com/jisungin/domain/booklike/BookLike.java
  src/main/java/com/jisungin/domain/mylibrary/UserLibrary.java
  src/main/java/com/jisungin/domain/review/Review.java
  src/main/java/com/jisungin/domain/review/repository/ReviewRepository.java
  src/main/java/com/jisungin/domain/talkroom/TalkRoom.java
  src/test/java/com/jisungin/api/book/BookControllerTest.java
  src/test/java/com/jisungin/api/talkroom/TalkRoomControllerTest.java
  src/test/java/com/jisungin/application/service/book/BookServiceTest.java
  src/test/java/com/jisungin/application/service/talkroom/TalkRoomServiceTest.java
Labels: ✨ Feature

#16 [Feature] Spring MVC 인증 기능 구현
  src/main/java/com/jisungin/api/oauth/Auth.java
  src/main/java/com/jisungin/api/oauth/AuthArgumentResolver.java
  src/main/java/com/jisungin/api/oauth/AuthConstant.java
  src/main/java/com/jisungin/api/oauth/AuthContext.java
  src/main/java/com/jisungin/api/oauth/AuthInterceptor.java
  src/main/java/com/jisungin/api/oauth/OauthController.java
  src/main/java/com/jisungin/application/oauth/OauthService.java
  src/main/java/com/jisungin/application/talkroom/TalkRoomService.java
  src/main/java/com/jisungin/config/AuthConfig.java
  src/main/java/com/jisungin/domain/oauth/client/UserClient.java
  src/main/java/com/jisungin/domain/oauth/client/UserClientComposite.java
  src/main/java/com/jisungin/domain/user/User.java
  src/main/java/com/jisungin/exception/ErrorCode.java
  src/main/java/com/jisungin/infra/oauth/kakao/KakaoOauthConfig.java
  src/main/java/com/jisungin/infra/oauth/kakao/KakaoUserClient.java
  src/main/java/com/jisungin/infra/oauth/kakao/client/KakaoApiClient.java
Labels: ✨ Feature

#23 [Refactor] TalkRoom API 리펙토링
  src/main/java/com/jisungin/api/talkroom/TalkRoomController.java
  src/main/java/com/jisungin/api/talkroom/request/TalkRoomCreateRequest.java
  src/main/java/com/jisungin/api/talkroom/request/TalkRoomEditRequest.java
  src/main/java/com/jisungin/application/talkroom/TalkRoomService.java
  src/main/java/com/jisungin/application/talkroom/request/TalkRoomCreateServiceRequest.java
  src/main/java/com/jisungin/application/talkroom/request/TalkRoomEditServiceRequest.java
  src/main/java/com/jisungin/application/talkroom/response/TalkRoomQueryResponse.java
  src/main/java/com/jisungin/application/talkroom/response/TalkRoomResponse.java
  src/main/java/com/jisungin/domain/talkroom/TalkRoom.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepository.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryCustom.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryImpl.java
  src/test/java/com/jisungin/api/talkroom/TalkRoomControllerTest.java
  src/test/java/com/jisungin/application/service/talkroom/TalkRoomServiceTest.java
Labels: 🔨 Refactor

#25 [Deploy] `jisungin.co.kr` 배포 설정
  .github/workflows/jisungin_dev.yml
  Dockerfile
  docker-compose.yml
  src/test/java/com/jisungin/application/service/book/BookServiceTest.java
  src/test/resources/application.yml
Labels: 🌏 Deploy

#26 [Refactor] Book 등록 API 수정
  src/main/java/com/jisungin/api/book/request/BookCreateRequest.java
  src/main/java/com/jisungin/application/book/BookService.java
  src/main/java/com/jisungin/application/book/request/BookCreateServiceRequest.java
  src/main/java/com/jisungin/application/book/response/BookResponse.java
  src/main/java/com/jisungin/application/talkroom/TalkRoomService.java
  src/main/java/com/jisungin/domain/book/Book.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryImpl.java
  src/main/java/com/jisungin/infra/crawler/CrawlingBook.java
  src/test/java/com/jisungin/api/book/BookControllerTest.java
  src/test/java/com/jisungin/api/talkroom/TalkRoomControllerTest.java
  src/test/java/com/jisungin/application/service/talkroom/TalkRoomServiceTest.java
  src/test/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryImplTest.java
Labels: 🔨 Refactor

#28 [Feature] TalkRoom Comment 등록 API 구현
  src/main/java/com/jisungin/api/comment/CommentController.java
  src/main/java/com/jisungin/api/comment/request/CommentCreateRequest.java
  src/main/java/com/jisungin/application/comment/CommentService.java
  src/main/java/com/jisungin/application/comment/request/CommentCreateServiceRequest.java
  src/main/java/com/jisungin/application/comment/response/CommentResponse.java
  src/main/java/com/jisungin/domain/comment/Comment.java
  src/main/java/com/jisungin/domain/comment/repository/CommentRepository.java
  src/test/java/com/jisungin/api/comment/CommentControllerTest.java
  src/test/java/com/jisungin/application/comment/CommentServiceTest.java
Labels: ✨ Feature

#30 [Test] Book API 테스트 수정
  src/test/java/com/jisungin/api/book/BookControllerTest.java
  src/test/java/com/jisungin/application/service/book/BookServiceTest.java
Labels: ✅ Test

#32 [Test] TalkRoom API 테스트 수정
  src/main/java/com/jisungin/api/talkroom/TalkRoomController.java
  src/main/java/com/jisungin/application/talkroom/TalkRoomService.java
  src/main/java/com/jisungin/application/talkroom/response/TalkRoomResponse.java
  src/main/java/com/jisungin/domain/talkroom/TalkRoom.java
  src/test/java/com/jisungin/ControllerTestSupport.java
  src/test/java/com/jisungin/ServiceTestSupport.java
  src/test/java/com/jisungin/api/comment/CommentControllerTest.java
  src/test/java/com/jisungin/api/talkroom/TalkRoomControllerTest.java
  src/test/java/com/jisungin/application/comment/CommentServiceTest.java
  src/test/java/com/jisungin/application/service/talkroom/TalkRoomServiceTest.java
Labels: ✅ Test

#35 [Feature] TalkRoom 단건 조회 API 구현
  src/main/java/com/jisungin/api/talkroom/TalkRoomController.java
  src/main/java/com/jisungin/application/talkroom/TalkRoomService.java
  src/main/java/com/jisungin/application/talkroom/response/TalkRoomFindAllResponse.java
  src/main/java/com/jisungin/application/talkroom/response/TalkRoomFindOneResponse.java
  src/main/java/com/jisungin/application/talkroom/response/TalkRoomQueryComments.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryCustom.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryImpl.java
  src/test/java/com/jisungin/RepositoryTestSupport.java
  src/test/java/com/jisungin/api/talkroom/TalkRoomControllerTest.java
  src/test/java/com/jisungin/application/service/talkroom/TalkRoomServiceTest.java
  src/test/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryImplTest.java
Labels: ✨ Feature

#37 [Feature] TalkRoom 삭제 API 구현
  src/main/java/com/jisungin/api/ApiResponse.java
  src/main/java/com/jisungin/api/talkroom/TalkRoomController.java
  src/main/java/com/jisungin/application/talkroom/TalkRoomService.java
  src/main/java/com/jisungin/domain/comment/repository/CommentRepository.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryImpl.java
  src/test/java/com/jisungin/api/talkroom/TalkRoomControllerTest.java
  src/test/java/com/jisungin/application/service/talkroom/TalkRoomServiceTest.java
Labels: ✨ Feature

#39 [Feature] TalkRoom Comment 수정, 삭제 API 구현
  src/main/java/com/jisungin/api/comment/CommentController.java
  src/main/java/com/jisungin/api/comment/request/CommentEditRequest.java
  src/main/java/com/jisungin/application/comment/CommentService.java
  src/main/java/com/jisungin/application/comment/request/CommentEditServiceRequest.java
  src/main/java/com/jisungin/application/talkroom/TalkRoomService.java
  src/main/java/com/jisungin/domain/comment/Comment.java
  src/main/java/com/jisungin/domain/talkroom/TalkRoom.java
  src/main/java/com/jisungin/exception/ErrorCode.java
  src/test/java/com/jisungin/api/comment/CommentControllerTest.java
  src/test/java/com/jisungin/application/comment/CommentServiceTest.java
Labels: ✨ Feature

#42 [Feature] 베스트 셀러 크롤링 기능 추가
  .github/workflows/jisungin_dev.yml
  .gitignore
  build.gradle
  src/main/java/com/jisungin/exception/ErrorCode.java
  src/main/java/com/jisungin/infra/crawler/Crawler.java
  src/main/java/com/jisungin/infra/crawler/CrawlingBook.java
  src/main/java/com/jisungin/infra/crawler/Fetcher.java
  src/main/java/com/jisungin/infra/crawler/Parser.java
  src/main/java/com/jisungin/infra/crawler/Yes24Crawler.java
  src/main/java/com/jisungin/infra/crawler/Yes24CrawlerConstant.java
  src/main/java/com/jisungin/infra/crawler/Yes24Fetcher.java
  src/main/java/com/jisungin/infra/crawler/Yes24Parser.java
  src/main/resources/application.yml
  src/test/java/com/jisungin/application/service/book/BookServiceTest.java
  src/test/java/com/jisungin/infra/Yes24CrawlerTest.java
  src/test/resources/application.yml
Labels: ✨ Feature

#49 [Docs] TalkRoom, Comment REST Dosc 작성
  src/docs/asciidoc/api/comment/comment.adoc
  src/docs/asciidoc/api/commentlike/commentlike.adoc
  src/docs/asciidoc/api/talkroom/talkroom.adoc
  src/docs/asciidoc/api/talkroomlike/talkroomlike.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/jisungin/api/SearchRequest.java
  src/main/java/com/jisungin/api/comment/CommentController.java
  src/main/java/com/jisungin/api/talkroom/TalkRoomController.java
  src/main/java/com/jisungin/api/talkroomlike/TalkRoomLikeController.java
  src/main/java/com/jisungin/application/SearchServiceRequest.java
  src/main/java/com/jisungin/application/comment/CommentService.java
  src/main/java/com/jisungin/application/talkroom/TalkRoomService.java
  src/main/java/com/jisungin/application/talkroomlike/TalkRoomLikeService.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryCustom.java
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryImpl.java
  src/test/java/com/jisungin/application/comment/CommentServiceTest.java
  src/test/java/com/jisungin/application/service/talkroom/TalkRoomServiceTest.java
  src/test/java/com/jisungin/application/talkroomlike/TalkRoomLikeServiceTest.java
  src/test/java/com/jisungin/docs/RestDocsSupport.java
  src/test/java/com/jisungin/docs/comment/CommentControllerDocsTest.java
  src/test/java/com/jisungin/docs/commentlike/CommentLikeControllerDocsTest.java
  src/test/java/com/jisungin/docs/talkroom/TalkRoomControllerDocsTest.java
  src/test/java/com/jisungin/docs/talkroomlike/TalkRoomLikeControllerDocsTest.java
  src/test/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryTest.java
  src/test/resources/org/springframework/restdocs/templates/path-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/query-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: 📃 Docs

#51 [Setting] REST Docs 그래들 설정 변경
  build.gradle
Labels: ⚙ Setting

#53 [Feature] 나의 토크방 모아보기 Query 작성
  src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryImpl.java
Labels: ✨ Feature

#54 [Feature] 사용자 별점 조회 API 구현
  src/main/java/com/jisungin/api/user/UserController.java
  src/main/java/com/jisungin/api/user/request/UserRatingGetAllRequest.java
  src/main/java/com/jisungin/application/review/response/RatingFindAllResponse.java
  src/main/java/com/jisungin/application/user/UserService.java
  src/main/java/com/jisungin/application/user/request/UserRatingGetAllServiceRequest.java
  src/main/java/com/jisungin/domain/review/RatingOrderType.java
  src/main/java/com/jisungin/domain/review/repository/ReviewRepository.java
  src/main/java/com/jisungin/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/jisungin/domain/review/repository/ReviewRepositoryImpl.java
  src/test/java/com/jisungin/ControllerTestSupport.java
  src/test/java/com/jisungin/api/user/UserControllerTest.java
  src/test/java/com/jisungin/application/user/UserServiceTest.java
  src/test/java/com/jisungin/domain/review/repository/ReviewRepositoryTest.java
Labels: ✨ Feature
